pub(super) const PATTERNS: &[&str] = &[
    "ignore previous",
    "ignore all previous",
    "ignore the above",
    "disregard previous",
    "disregard all",
    "forget everything",
    "forget previous",
    "forget all previous",
    "you are now",
    "you're now",
    "act as",
    "pretend you are",
    "pretend to be",
    "roleplay as",
    "new instructions:",
    "new instructions follow",
    "new system prompt",
    "system prompt:",
    "reveal your prompt",
    "reveal your instructions",
    "show me your prompt",
    "show me your instructions",
    "your real instructions",
    "your true instructions",
    "ignore your training",
    "jailbreak",
    "dan mode",
    "developer mode",
    "admin override",
    "admin mode",
    "do anything now",
    "no restrictions",
    "<|im_end|>",
    "<|im_start|>",
];
