pub(super) const PATTERNS: &[&str] = &[
    "zignoruj poprzednie",
    "zignoruj wszystkie poprzednie",
    "zignoruj powyższe",
    "zapomnij poprzednie",
    "zapomnij wszystko",
    "jesteś teraz",
    "udawaj że jesteś",
    "udawaj że",
    "działaj jako",
    "graj rolę",
    "nowe instrukcje:",
    "nowy prompt systemowy",
    "prompt systemowy:",
    "ujawnij prompt",
    "ujawnij instrukcje",
    "pokaż prompt",
    "pokaż swoje instrukcje",
    "pokaż system prompt",
    "omiń",
    "tryb dewelopera",
    "tryb administratora",
    "bez ograniczeń",
];
